# make use of vm's
sudo: 'required'

# have the docker service set up (we'll update it later)
services:
  - 'docker'

env:
  - JACKETT_VER=latest
  - JACKETT_VER=0.11.487

# prepare the machine before any code installation scripts
before_install:
  - './.travis/main.sh'

# first execute the test suite.
# after the test execution is done and didn't fail, build the images
# (if this step fails the whole Travis build is considered a failure).
script:
  - 'make test'
  - 'make image'

deploy:
  provider: script
  script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && make push
  on:
    branch: master
